feat: Generate diag when test fails
splunk/addonfactory-workflow-addon-release pull request #126
Opened 2023-01-19 09:10 UTC by truptilangalia-crest

- Added support to store diag in artifacts for the failing test types.

2023-01-19 12:58 UTC, uoboda-splunk requested changes

2023-01-19 12:58 UTC, uoboda-splunk commented on .github/workflows/reusable-build-test-release.yml
> +          echo "::set-output name=argo-workflow-tmpl-name::ta-workflow-splunk-diag"
it should be changed to the previous name I guess?

2023-01-19 13:21 UTC, uoboda-splunk submitted a review, later dismissed

2023-01-20 09:27 UTC, bhargav-nariyani-crest approved these changes

2023-01-20 10:06 UTC, closed without merging