chore: replace LastPass information with SecretServer
splunk/addonfactory-workflow-addon-release pull request #177
Opened 2023-09-12 07:42 UTC by mkolasinski-splunk

As LastPass is being deprecated in Splunk, we need to update related information and direct to Secret Server.
More info:
https://docs.google.com/document/d/1sRYlWG22gpEJyltgchP0RQMeBqsFAjhlDQiTspp9zgA/edit

2023-09-12 07:56 UTC, artemrys requested changes
Please change it in other places as well in this file.

2023-09-12 08:15 UTC, mkolasinski-splunk commented
@artemrys done

2023-09-13 10:10 UTC, artemrys approved these changes

2023-09-13 10:10 UTC, merged

2023-09-13 10:13 UTC, srv-rr-github-token commented
:tada: This PR is included in version 4.6.1 :tada:

The release is available on [GitHub release](https://github.com/splunk/addonfactory-workflow-addon-release/releases/tag/v4.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: