feat: pre-publish job adjusted to triggering event
splunk/addonfactory-workflow-addon-release pull request #212
Opened 2024-01-03 15:34 UTC by kdoroszko-splunk

This PR regards https://splunk.atlassian.net/browse/ADDON-67617
It introduces dynamic change of pre-publish job which was necessary to avoid confusion while creating PR towards main branch having had pushed to develop branch. 

tests: 
- push to develop: https://github.com/splunk/splunk-add-on-for-mysql/actions/runs/7399079510
- pr to main: https://github.com/splunk/splunk-add-on-for-mysql/actions/runs/7399125452

2024-01-03 16:02 UTC, mbruzda-splunk requested changes

2024-01-03 16:02 UTC, mbruzda-splunk commented on .github/workflows/reusable-build-test-release.yml
> +    # The following line will rename 'pre-bublish' to 'pre-publish-not_main_pr' when PR is created towards main branch
`pre-bublish` 🤣

2024-01-03 16:08 UTC, kdoroszko-splunk commented on .github/workflows/reusable-build-test-release.yml
> +    # The following line will rename 'pre-bublish' to 'pre-publish-not_main_pr' when PR is created towards main branch
fixed 😄

2024-01-03 16:18 UTC, mbruzda-splunk approved these changes

2024-01-04 11:45 UTC, artemrys approved these changes

2024-01-04 11:45 UTC, merged