chore: remove firefox from ui tests
splunk/addonfactory-workflow-addon-release pull request #228
Opened 2024-02-07 14:25 UTC by kdoroszko-splunk

This PR removes firefox from ui tests execution, since firefox is ranked 4th in Desktop Browser Market Share Worldwide.
https://splunk.atlassian.net/browse/ADDON-68235
tested here: https://github.com/splunk/test-addonfactory-repo/actions/runs/7815971598/job/21320701943

2024-02-07 16:03 UTC, artemrys requested changes
Let's have it as a `feat` because it is a customer-facing change.

2024-02-07 16:07 UTC, kdoroszko-splunk commented
> Let's have it as a `feat` because it is a customer-facing change.

Good point, done.

2024-02-07 16:08 UTC, artemrys approved these changes

2024-02-07 16:17 UTC, merged

2024-04-17 11:26 UTC, srv-rr-github-token commented
:tada: This PR is included in version 4.16.0 :tada:

The release is available on [GitHub release](https://github.com/splunk/addonfactory-workflow-addon-release/releases/tag/v4.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: