docs: update setup-workflow description in README.md
splunk/addonfactory-workflow-addon-release pull request #315
Opened 2024-08-29 12:16 UTC by kdoroszko-splunk

Updating README.md to be aligned with the latest changes (https://github.com/splunk/addonfactory-workflow-addon-release/pull/309).

2024-08-29 16:19 UTC, mkolasinski-splunk requested changes

2024-08-29 16:19 UTC, mkolasinski-splunk commented on README.md
> +    * when `execute-tests-on-push-to-develop` is set to 'false' tests will not be triggered
```suggestion
```
No longer valid according to latest changes.

2024-08-30 08:54 UTC, awownysz-splunk approved these changes

2024-08-30 10:08 UTC, mkolasinski-splunk approved these changes

2024-08-30 10:51 UTC, merged

2024-09-03 13:43 UTC, srv-rr-github-token commented
:tada: This PR is included in version 4.17.0 :tada:

The release is available on [GitHub release](https://github.com/splunk/addonfactory-workflow-addon-release/releases/tag/v4.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: